[package]
name = "poulpy-schemes"
version = "0.3.3"
edition = "2024"
license = "Apache-2.0"
readme = "README.md"
description = "A backend agnostic crate implementing mainsteam RLWE-based FHE schemes"
repository = "https://github.com/phantomzone-org/poulpy"
homepage = "https://github.com/phantomzone-org/poulpy"
documentation = "https://docs.rs/poulpy"

[dependencies]
poulpy-cpu-avx = {workspace = true}
poulpy-cpu-ref = {workspace = true}
poulpy-hal = {workspace = true}
poulpy-core = {workspace = true}
criterion = {workspace = true}
itertools = "0.14.0"
byteorder = "1.5.0"
rand = "0.9.2"
paste = "1.0.15"

[[bench]]
name = "circuit_bootstrapping"
harness = false